build.env usr/share/doc/immich-server
debian/wrappers/immich-admin usr/sbin
plugins/dist usr/share/immich/plugins
plugins/manifest.json usr/share/immich/plugins
server/bin/get-cpus.sh usr/lib/immich/server/bin
usr/lib/immich/.build/build-lock.json
usr/lib/immich/server/.pnpm-store
usr/lib/immich/server/dist
usr/lib/immich/server/helmet.json
usr/lib/immich/server/node_modules
usr/lib/immich/server/package.json
usr/lib/immich/server/pnpm-lock.yaml
usr/share/doc/immich-server
