plugins/dist usr/share/immich/plugins
plugins/manifest.json usr/share/immich/plugins
server/bin/get-cpus.sh usr/lib/immich/server/bin
debian/wrappers/immich-admin usr/sbin
usr/lib/immich/server/.pnpm-store
usr/lib/immich/server/dist
usr/lib/immich/server/node_modules
usr/lib/immich/server/package.json
usr/lib/immich/server/pnpm-lock.yaml
usr/lib/immich/server/resources
usr/share/doc/immich-server
